image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

build-and-test-viper:
  script:
    - rm -rf ${PWD}/artifacts/ && mkdir ${PWD}/artifacts/
    - docker build --no-cache -t viper-docker-build .
    - docker run --rm -v ${PWD}/artifacts:/artifacts viper-docker-build
    - docker rmi viper-docker-build
  artifacts:
    paths:
    - artifacts/
    expire_in: 1 month
